definitions:
  models.Author:
    properties:
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      photo_link:
        type: string
    type: object
  models.Book:
    properties:
      author_id:
        type: string
      id:
        type: string
      photo_link:
        type: string
      title:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  title: Mybook API
  version: "1.0"
paths:
  /author/create:
    post:
      consumes:
      - application/json
      description: This api is using create new author
      parameters:
      - description: author body
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/models.Author'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create authors summary
      tags:
      - Author
  /book/create:
    post:
      consumes:
      - application/json
      description: This api is using create new book
      parameters:
      - description: book body
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create books summary
      tags:
      - Book
  /user/create:
    post:
      consumes:
      - application/json
      description: This api is using create new user
      parameters:
      - description: user body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create users summary
      tags:
      - User
swagger: "2.0"
